// All 189 domain cards (levels 1-10). Source: CoreBook Appendix p.329-345.
// Card display text (name/description) lives in i18n under `dh.card.<id>` / `_desc`.

import type { DomainKey } from "./types";

export type CardType = "ability" | "spell" | "grimoire";

export interface DomainCardDef {
  id: string;
  domain: DomainKey;
  level: number;
  type: CardType;
  recallCost: number;
}

const c = (
  id: string,
  domain: DomainKey,
  level: number,
  type: CardType,
  recallCost: number,
): DomainCardDef => ({ id, domain, level, type, recallCost });

export const DOMAIN_CARDS: DomainCardDef[] = [
  // ── Level 1 ──
  c("arcana_rune_ward", "arcana", 1, "spell", 0),
  c("arcana_unleash_chaos", "arcana", 1, "spell", 1),
  c("arcana_wall_walk", "arcana", 1, "spell", 1),
  c("blade_get_back_up", "blade", 1, "ability", 1),
  c("blade_not_good_enough", "blade", 1, "ability", 1),
  c("blade_whirlwind", "blade", 1, "ability", 0),
  c("bone_deft_maneuvers", "bone", 1, "ability", 0),
  c("bone_i_see_it_coming", "bone", 1, "ability", 1),
  c("bone_untouchable", "bone", 1, "ability", 1),
  c("codex_book_of_ava", "codex", 1, "grimoire", 2),
  c("codex_book_of_illiat", "codex", 1, "grimoire", 2),
  c("codex_book_of_tyfar", "codex", 1, "grimoire", 2),
  c("grace_deft_deceiver", "grace", 1, "ability", 0),
  c("grace_enrapture", "grace", 1, "spell", 0),
  c("grace_inspirational", "grace", 1, "ability", 1),
  c("midnight_disguise", "midnight", 1, "ability", 0),
  c("midnight_pick_pull", "midnight", 1, "spell", 1),
  c("midnight_rain_blades", "midnight", 1, "spell", 0),
  c("sage_gifted_tracker", "sage", 1, "ability", 0),
  c("sage_natures_tongue", "sage", 1, "ability", 0),
  c("sage_vicious_entangle", "sage", 1, "spell", 1),
  c("splendor_bolt_beacon", "splendor", 1, "spell", 1),
  c("splendor_mending_touch", "splendor", 1, "spell", 1),
  c("splendor_reassurance", "splendor", 1, "ability", 0),
  c("valor_bare_bones", "valor", 1, "ability", 0),
  c("valor_forceful_push", "valor", 1, "ability", 0),
  c("valor_i_am_shield", "valor", 1, "ability", 1),

  // ── Level 2 ──
  c("arcana_cinder_grasp", "arcana", 2, "spell", 1),
  c("arcana_floating_eye", "arcana", 2, "spell", 0),
  c("blade_a_soldiers_bond", "blade", 2, "ability", 1),
  c("blade_reckless", "blade", 2, "ability", 1),
  c("bone_ferocity", "bone", 2, "ability", 2),
  c("bone_strategic_approach", "bone", 2, "ability", 1),
  c("codex_book_of_sitil", "codex", 2, "grimoire", 2),
  c("codex_book_of_vagras", "codex", 2, "grimoire", 2),
  c("grace_tell_no_lies", "grace", 2, "spell", 1),
  c("grace_troublemaker", "grace", 2, "ability", 2),
  c("midnight_midnight_spirit", "midnight", 2, "spell", 1),
  c("midnight_shadowbind", "midnight", 2, "spell", 0),
  c("sage_conjure_swarm", "sage", 2, "spell", 1),
  c("sage_natural_familiar", "sage", 2, "spell", 1),
  c("splendor_final_words", "splendor", 2, "spell", 1),
  c("splendor_healing_hands", "splendor", 2, "spell", 1),
  c("valor_body_basher", "valor", 2, "ability", 1),
  c("valor_bold_presence", "valor", 2, "ability", 0),

  // ── Level 3 ──
  c("arcana_counterspell", "arcana", 3, "spell", 2),
  c("arcana_flight", "arcana", 3, "spell", 1),
  c("blade_scramble", "blade", 3, "ability", 1),
  c("blade_versatile_fighter", "blade", 3, "ability", 1),
  c("bone_brace", "bone", 3, "ability", 1),
  c("bone_tactician", "bone", 3, "ability", 1),
  c("codex_book_of_korvax", "codex", 3, "grimoire", 2),
  c("codex_book_of_norai", "codex", 3, "grimoire", 2),
  c("grace_hypnotic_shimmer", "grace", 3, "spell", 1),
  c("grace_invisibility", "grace", 3, "spell", 1),
  c("midnight_chokehold", "midnight", 3, "ability", 1),
  c("midnight_veil_of_night", "midnight", 3, "spell", 1),
  c("sage_corrosive_projectile", "sage", 3, "spell", 1),
  c("sage_towering_stalk", "sage", 3, "spell", 1),
  c("splendor_second_wind", "splendor", 3, "ability", 2),
  c("splendor_voice_of_reason", "splendor", 3, "ability", 1),
  c("valor_critical_inspiration", "valor", 3, "ability", 1),
  c("valor_lean_on_me", "valor", 3, "ability", 1),

  // ── Level 4 ──
  c("arcana_blink_out", "arcana", 4, "spell", 1),
  c("arcana_preservation_blast", "arcana", 4, "spell", 2),
  c("blade_deadly_focus", "blade", 4, "ability", 2),
  c("blade_fortified_armor", "blade", 4, "ability", 0),
  c("bone_boost", "bone", 4, "ability", 1),
  c("bone_redirect", "bone", 4, "ability", 1),
  c("codex_book_of_exota", "codex", 4, "grimoire", 3),
  c("codex_book_of_grynn", "codex", 4, "grimoire", 2),
  c("grace_soothing_speech", "grace", 4, "ability", 1),
  c("grace_through_your_eyes", "grace", 4, "spell", 1),
  c("midnight_glyph_of_nightfall", "midnight", 4, "spell", 1),
  c("midnight_stealth_expertise", "midnight", 4, "ability", 0),
  c("sage_death_grip", "sage", 4, "spell", 1),
  c("sage_healing_field", "sage", 4, "spell", 2),
  c("splendor_divination", "splendor", 4, "spell", 1),
  c("splendor_life_ward", "splendor", 4, "spell", 1),
  c("valor_goad_them_on", "valor", 4, "ability", 1),
  c("valor_support_tank", "valor", 4, "ability", 2),

  // ── Level 5 ──
  c("arcana_chain_lightning", "arcana", 5, "spell", 1),
  c("arcana_premonition", "arcana", 5, "spell", 2),
  c("blade_champions_edge", "blade", 5, "ability", 1),
  c("blade_vitality", "blade", 5, "ability", 0),
  c("bone_know_thy_enemy", "bone", 5, "ability", 1),
  c("bone_signature_move", "bone", 5, "ability", 1),
  c("codex_manifest_wall", "codex", 5, "spell", 2),
  c("codex_teleport", "codex", 5, "spell", 2),
  c("grace_thought_delver", "grace", 5, "spell", 2),
  c("grace_words_of_discord", "grace", 5, "spell", 1),
  c("midnight_hush", "midnight", 5, "spell", 1),
  c("midnight_phantom_retreat", "midnight", 5, "spell", 2),
  c("sage_thorn_skin", "sage", 5, "spell", 1),
  c("sage_wild_fortress", "sage", 5, "spell", 1),
  c("splendor_shape_material", "splendor", 5, "spell", 1),
  c("splendor_smite", "splendor", 5, "spell", 2),
  c("valor_armorer", "valor", 5, "ability", 1),
  c("valor_rousing_strike", "valor", 5, "ability", 1),

  // ── Level 6 ──
  c("arcana_rift_walker", "arcana", 6, "spell", 2),
  c("arcana_telekinesis", "arcana", 6, "spell", 0),
  c("blade_battle_hardened", "blade", 6, "ability", 2),
  c("blade_rage_up", "blade", 6, "ability", 1),
  c("bone_rapid_riposte", "bone", 6, "ability", 0),
  c("bone_recovery", "bone", 6, "ability", 1),
  c("codex_banish", "codex", 6, "spell", 0),
  c("codex_sigil_of_retribution", "codex", 6, "spell", 2),
  c("grace_never_upstaged", "grace", 6, "ability", 2),
  c("grace_share_the_burden", "grace", 6, "spell", 0),
  c("midnight_dark_whispers", "midnight", 6, "spell", 0),
  c("midnight_mass_disguise", "midnight", 6, "spell", 0),
  c("sage_conjured_steeds", "sage", 6, "spell", 0),
  c("sage_forager", "sage", 6, "ability", 1),
  c("splendor_restoration", "splendor", 6, "spell", 2),
  c("splendor_zone_of_protection", "splendor", 6, "spell", 2),
  c("valor_inevitable", "valor", 6, "ability", 1),
  c("valor_rise_up", "valor", 6, "ability", 2),

  // ── Level 7 ──
  c("arcana_arcana_touched", "arcana", 7, "ability", 2),
  c("arcana_cloaking_blast", "arcana", 7, "spell", 2),
  c("blade_blade_touched", "blade", 7, "ability", 1),
  c("blade_glancing_blow", "blade", 7, "ability", 1),
  c("bone_bone_touched", "bone", 7, "ability", 2),
  c("bone_cruel_precision", "bone", 7, "ability", 1),
  c("codex_book_of_homet", "codex", 7, "grimoire", 0),
  c("codex_codex_touched", "codex", 7, "ability", 2),
  c("grace_endless_charisma", "grace", 7, "ability", 1),
  c("grace_grace_touched", "grace", 7, "ability", 2),
  c("midnight_midnight_touched", "midnight", 7, "ability", 2),
  c("midnight_vanishing_dodge", "midnight", 7, "spell", 1),
  c("sage_sage_touched", "sage", 7, "ability", 2),
  c("sage_wild_surge", "sage", 7, "spell", 2),
  c("splendor_healing_strike", "splendor", 7, "spell", 1),
  c("splendor_splendor_touched", "splendor", 7, "ability", 2),
  c("valor_shrug_it_off", "valor", 7, "ability", 1),
  c("valor_valor_touched", "valor", 7, "ability", 1),

  // ── Level 8 ──
  c("arcana_arcane_reflection", "arcana", 8, "spell", 1),
  c("arcana_confusing_aura", "arcana", 8, "spell", 2),
  c("blade_battle_cry", "blade", 8, "ability", 2),
  c("blade_frenzy", "blade", 8, "ability", 3),
  c("bone_breaking_blow", "bone", 8, "ability", 3),
  c("bone_wrangle", "bone", 8, "ability", 1),
  c("codex_book_of_vyola", "codex", 8, "grimoire", 2),
  c("codex_safe_haven", "codex", 8, "spell", 3),
  c("grace_astral_projection", "grace", 8, "spell", 0),
  c("grace_mass_enrapture", "grace", 8, "spell", 3),
  c("midnight_shadowhunter", "midnight", 8, "ability", 2),
  c("midnight_spellcharge", "midnight", 8, "spell", 1),
  c("sage_forest_sprites", "sage", 8, "spell", 2),
  c("sage_rejuvenation_barrier", "sage", 8, "spell", 1),
  c("splendor_shield_aura", "splendor", 8, "spell", 2),
  c("splendor_stunning_sunlight", "splendor", 8, "spell", 2),
  c("valor_full_surge", "valor", 8, "ability", 1),
  c("valor_ground_pound", "valor", 8, "ability", 2),

  // ── Level 9 ──
  c("arcana_earthquake", "arcana", 9, "spell", 2),
  c("arcana_sensory_projection", "arcana", 9, "spell", 0),
  c("blade_gore_and_glory", "blade", 9, "ability", 2),
  c("blade_reapers_strike", "blade", 9, "ability", 3),
  c("bone_on_the_brink", "bone", 9, "ability", 1),
  c("bone_splintering_strike", "bone", 9, "ability", 3),
  c("codex_book_of_ronin", "codex", 9, "grimoire", 4),
  c("codex_disintegration_wave", "codex", 9, "spell", 4),
  c("grace_copycat", "grace", 9, "spell", 3),
  c("grace_master_of_the_craft", "grace", 9, "ability", 0),
  c("midnight_night_terror", "midnight", 9, "spell", 2),
  c("midnight_twilight_toll", "midnight", 9, "ability", 1),
  c("sage_fane_of_the_wilds", "sage", 9, "ability", 2),
  c("sage_plant_dominion", "sage", 9, "spell", 1),
  c("splendor_overwhelming_aura", "splendor", 9, "spell", 2),
  c("splendor_salvation_beam", "splendor", 9, "spell", 2),
  c("valor_hold_the_line", "valor", 9, "ability", 1),
  c("valor_lead_by_example", "valor", 9, "ability", 3),

  // ── Level 10 ──
  c("arcana_adjust_reality", "arcana", 10, "spell", 1),
  c("arcana_falling_sky", "arcana", 10, "spell", 1),
  c("blade_battle_monster", "blade", 10, "ability", 0),
  c("blade_onslaught", "blade", 10, "ability", 3),
  c("bone_deathrun", "bone", 10, "ability", 1),
  c("bone_swift_step", "bone", 10, "ability", 2),
  c("codex_book_of_yarrow", "codex", 10, "grimoire", 2),
  c("codex_transcendent_union", "codex", 10, "spell", 1),
  c("grace_encore", "grace", 10, "spell", 1),
  c("grace_notorious", "grace", 10, "ability", 0),
  c("midnight_eclipse", "midnight", 10, "spell", 2),
  c("midnight_specter_of_the_dark", "midnight", 10, "spell", 1),
  c("sage_force_of_nature", "sage", 10, "spell", 2),
  c("sage_tempest", "sage", 10, "spell", 2),
  c("splendor_invigoration", "splendor", 10, "spell", 3),
  c("splendor_resurrection", "splendor", 10, "spell", 2),
  c("valor_unbreakable", "valor", 10, "ability", 4),
  c("valor_unyielding_armor", "valor", 10, "ability", 1),
];

export const CARDS_BY_ID: Record<string, DomainCardDef> = Object.fromEntries(
  DOMAIN_CARDS.map((c) => [c.id, c]),
);

export function cardsForDomains(domains: [DomainKey, DomainKey], level = 1): DomainCardDef[] {
  return DOMAIN_CARDS.filter((c) => domains.includes(c.domain) && c.level <= level);
}
